config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'

  namespace :api do
    namespace :v1 do
      resources :users, param: :id, only: [:index, :show] do
        resources :user_emotions, only: [:index, :destroy] do
          collection do
            get :graph_data
          end
        end
        resources :entries, except: [:new]
        resources :journals, only: [:index, :destroy]
        resources :goals, only: [:index, :destroy]
      end
      resources :link_caches, only: [:index] do
        collection do
          get :random_articles
        end
      end
      namespace :users do
        get 'is_signed_in', to: 'users#show'
      end
    end
  end

  resources :entries, only: [:index, :show, :edit, :update, :destroy] do
    member do
      post :completed_goals
    end
  end
  resources :goals, only: [:index, :show, :edit, :update, :destroy]
  resources :journals, only: [:index, :show, :edit, :update, :destroy]
  resources :user_emotions, only: [:index, :show, :edit, :update, :destroy]
  resources :link_caches, only: [:index]

  get '*path', to: 'static_pages#index'
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :entry
end

app/controllers/api/v1/goals_controller.rb
class Api::V1::GoalsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  skip_before_action :verify_authenticity_token


  def index
    user = current_user
    goals = user.entries.order(created_at: :desc).map(&:goals)
    render json: goals
  end

  def destroy

  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @user = current_user
    @goal_entries = @user.entries.order(created_at: :desc).map { |entry| [entry, entry.goals.order(:id)] }
  end
end

app/views/goals/index.html.erb
<h1 class="past-goals-title">Past Goals</h1>
<div class="goals-index-container">
  <div class="goals-index">
    <div class="goals-outer-list">
      <% @goal_entries.each do |entry, goals| %>
        <div class="goals-list">
          <h3><%= entry.created_at.strftime('%a, %m/%d/%Y') %></h3>
          <%= form_tag(completed_goals_entry_path(entry)) do %>
            <% goals.each do |goal| %>
              <% if goal.goal_item.present? %>
                <div class="row goal-item">
                  <div class="small-1 large-1 columns">
                    <%= check_box_tag(goal.id, true, goal.completed, class: "checkbox") %>
                  </div>
                  <div class="small-11 large-11 columns">
                    <%= label_tag(goal.id, goal.goal_item) %>
                  </div>
                </div>
              <% end %>
            <% end %>
            <%= submit_tag "Update Goals", class: "button" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>