config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'

  namespace :api do
    namespace :v1 do
      resources :users, param: :id, only: [:index, :show] do
        resources :user_emotions, only: [:index, :destroy] do
          collection do
            get :graph_data
          end
        end
        resources :entries, except: [:new]
        resources :journals, only: [:index, :destroy]
        resources :goals, only: [:index, :destroy]
      end
      resources :link_caches, only: [:index] do
        collection do
          get :random_articles
        end
      end
      namespace :users do
        get 'is_signed_in', to: 'users#show'
      end
    end
  end

  resources :entries, only: [:index, :show, :edit, :update, :destroy] do
    member do
      post :completed_goals
    end
  end
  resources :goals, only: [:index, :show, :edit, :update, :destroy]
  resources :journals, only: [:index, :show, :edit, :update, :destroy]
  resources :user_emotions, only: [:index, :show, :edit, :update, :destroy]
  resources :link_caches, only: [:index]

  get '*path', to: 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  has_many :user_diagnoses
  has_many :users, through: :user_diagnoses
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  has_many :user_emotions
  has_many :users, through: :user_emotions

  EMOTIONS = [
    "happiness",
    "sadness",
    "excitement",
    "anger",
    "anxiety",
    "peacefulness"
  ]

  validates :feeling, inclusion: { in: EMOTIONS }
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :goals, dependent: :destroy
  has_many :journals, dependent: :destroy
  has_many :user_emotions, dependent: :destroy
  belongs_to :user

  def find_rating(feeling)
    emotion = Emotion.find_by_feeling(feeling)
    user_emotions.where(emotion: emotion).first.rating
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :entry
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  belongs_to :entry
end

app/models/link_cache.rb
class LinkCache < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_diagnoses
  has_many :diagnoses, through: :user_diagnoses
  has_many :goals
  has_many :journals
  has_many :user_emotions
  has_many :emotions, through: :user_emotions
  has_many :entries
  validates :username, presence: true, length: { in: 6..20 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :lgbtq, presence: true, numericality: true
end

app/models/user_diagnosis.rb
class UserDiagnosis < ApplicationRecord
  belongs_to :user
  belongs_to :diagnosis
end

app/models/user_emotion.rb
class UserEmotion < ApplicationRecord
  belongs_to :user
  belongs_to :emotion
  belongs_to :entry
  validates :rating, numericality: true

  def feeling
    emotion.feeling
  end
end

app/controllers/api/v1/goals_controller.rb
class Api::V1::GoalsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  skip_before_action :verify_authenticity_token


  def index
    user = current_user
    goals = user.entries.order(created_at: :desc).map(&:goals)
    render json: goals
  end

  def destroy

  end
end

app/controllers/api/v1/user_controller.rb
class Api::V1::UserController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
    users = User.all
  end

  def is_signed_in?
    if user_signed_in?
      render :json => {"signed_in" => true, "user" => current_user}
    else
      render :json => {"signed_in" => false}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> {request.format.json?}
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :lgbtq])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :lgbtq])
 end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def completed_goals
    entry = Entry.find(params[:id])
    goals = entry.goals
    goals.each do |goal|
      if params[goal.id.to_s]
        goal.completed = true
      else
        goal.completed = false
      end
      goal.save
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @user = current_user
    @goal_entries = @user.entries.order(created_at: :desc).map { |entry| [entry, entry.goals.order(:id)] }
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def index
    @user = current_user
    @journal_entries = @user.entries.order(created_at: :desc).map(&:journals)
  end
end

app/controllers/link_caches_controller.rb
class LinkCachesController < ApplicationController
  def index
    @link_cache = LinkCache.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/user_emotions_controller.rb
class UserEmotionsController < ApplicationController
  def index
    @user = current_user
    @happiness = UserEmotion.where(user_id: @user.id, emotion_id: Emotion.find_by(feeling: "happiness").id).order(created_at: :desc)
    @sadness = UserEmotion.where(user_id: @user.id, emotion_id: Emotion.find_by(feeling: "sadness").id).order(created_at: :desc)
    @excitement = UserEmotion.where(user_id: @user.id, emotion_id: Emotion.find_by(feeling: "excitement").id).order(created_at: :desc)
    @anger = UserEmotion.where(user_id: @user.id, emotion_id: Emotion.find_by(feeling: "anger").id).order(created_at: :desc)
    @anxiety = UserEmotion.where(user_id: @user.id, emotion_id: Emotion.find_by(feeling: "anxiety").id).order(created_at: :desc)
    @peacefulness = UserEmotion.where(user_id: @user.id, emotion_id: Emotion.find_by(feeling: "peacefulness").id).order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Thriver: A Wellness Tracker</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'index'   %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <div id="background-image">
    <body>
      <div>
        <div class="thriver-header">
          <header class="row">
            <h1 class="thriver"><%= link_to "Thriver", root_path %></h1><br /><span class="subheader">A Wellness Tracker</span>
          </header>
        </div>
      </div>
      <div>
        <nav class="top-bar" data-topbar role "navigation">
          <section class="top-bar-section">
             <ul class="right">
               <% if user_signed_in? %>
                 <li class="articles-and-resources-link-nav"><%= link_to "Articles & Resources", link_caches_path %></li>
                 <li class="has-dropdown">
                   <a href="#">See How Things Changed</a>
                   <ul class="dropdown">
                       <% user = current_user.id %>
                       <li><%= link_to "All Entries", entries_path %></li>
                       <li><%= link_to "Goals", goals_path %></li>
                       <li><%= link_to "Journal Entries", journals_path %></li>
                       <li><%= link_to "Emotion Ratings", user_emotions_path %></li>
                   </ul>
                 </li>
                 <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
                 <% else %>
                 <section class="top-bar-section">
                   <ul class="right">
                     <li><%= link_to "Log In", new_user_session_path %></li>
                     <li><%= link_to "Sign Up", new_user_registration_path %></li>
                   </ul>
                 </section>
                 <% end %>
           </section>
          </nav>
        </div>
      <div id="app">
      </div>
      <div id="server-side">
        <%= yield %>
      </div>
    </body>
  </div>
</html>